In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.svm import SVR

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

import mlflow

c:\Users\rajpu\OneDrive\Desktop\ML_REAL_PROJECT\my-uber-demand prediction\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
import dagshub
dagshub.init(repo_owner='rajputriya887', repo_name='uber-demand-prediction', mlflow=True)

Repository uber-demand-prediction doesn't exist, creating it under current user.

Initialized MLflow to track repo "rajputriya887/uber-demand-prediction"

Repository rajputriya887/uber-demand-prediction initialized!

In [7]:
# set the dagshub tracking server

mlflow.set_tracking_uri("https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow")

In [ ]:
# load the training and test data

train_data_path = "../data/processed/train.csv"
test_data_path = "../data/processed/test.csv"

train_df = pd.read_csv(train_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

test_df = pd.read_csv(test_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

train_df

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,12.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,14.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,15.0,0

In [9]:
# missing value in training data

train_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [10]:
# missing values in the test data

test_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [11]:
# make X_train and y_train

X_train = train_df.drop(columns=["total_pickups"])

y_train = train_df["total_pickups"]

In [12]:
X_train.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,140.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,161.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,175.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,177.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185.0,4

In [13]:
# make X_test and y_test

X_test = test_df.drop(columns=["total_pickups"])

y_test = test_df["total_pickups"]

In [14]:
X_test.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-03-01 00:00:00,36.0,44.0,31.0,29.0,0,38.0,1
2016-03-01 00:15:00,41.0,36.0,44.0,31.0,0,39.0,1
2016-03-01 00:30:00,35.0,41.0,36.0,44.0,0,37.0,1
2016-03-01 00:45:00,47.0,35.0,41.0,36.0,0,41.0,1
2016-03-01 01:00:00,34.0,47.0,35.0,41.0,0,38.0,1

In [15]:
from sklearn import set_config

set_config(transform_output="pandas")

In [16]:
# encode the data

encoder = ColumnTransformer([
    ("ohe", OneHotEncoder(drop="first",sparse_output=False), ["region","day_of_week"])
], remainder="passthrough", n_jobs=-1)

In [17]:
encoder

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['region', 'day_of_week'])])

In [18]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

In [20]:
import optuna
import tqdm

In [21]:
# set the experiment

mlflow.set_experiment("Model Selection")

2026/06/13 15:28:33 INFO mlflow.tracking.fluent: Experiment with name 'Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/38aa807d3665490fbc42be2265bdfad8', creation_time=1781344713767, effective_trace_archival_retention=None, experiment_id='0', last_update_time=1781344713767, lifecycle_stage='active', name='Model Selection', tags={}, trace_location=None, workspace='default'>

In [22]:
def objective(trial):
    # start the child run
    with mlflow.start_run(nested=True) as child:
        
        # model name search space
        list_of_models = ["LR", "RF", "GBR", "XGBR"]
        model_name = trial.suggest_categorical("model_name", list_of_models)
    
        if model_name == "LR":
            model = LinearRegression()
    
        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,100,step=10)
            max_depth_rf = trial.suggest_int("max_depth_rf",3,10)
            model = RandomForestRegressor(n_estimators=n_estimators_rf, 
                                          max_depth=max_depth_rf, 
                                          random_state=42, n_jobs=-1)
    
        elif model_name == "GBR":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,100,step=10)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",1e-4,1e-1, log=True)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb, 
                                              learning_rate=learning_rate_gb,
                                             random_state=42)
    
        elif model_name == "XGBR":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,100,step=10)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",1e-4,1e-1, log=True)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",3,10)
            model = XGBRegressor(n_estimators=n_estimators_xgb,
                                learning_rate=learning_rate_xgb,
                                max_depth=max_depth_xgb)
    
        # log the model name
        mlflow.log_param("model_name",model_name)
        
        # log the model parameters
        mlflow.log_params(model.get_params())
        
        # fit on the data
        model.fit(X_train_encoded,y_train)
    
        # get the predictions
        y_pred = model.predict(X_test_encoded)
    
        # calculate the loss
        loss = mean_absolute_percentage_error(y_test, y_pred)
    
        # log the metric
        mlflow.log_metric("MAPE",loss)
        return loss

In [23]:
# optimize the objective function

with mlflow.start_run(run_name="best_model", nested=True) as parent:

    # create a study object
    study = optuna.create_study(study_name="model_selection", direction="minimize")
    # optimize the objective function
    study.optimize(func=objective, n_trials=50, n_jobs=-1)
    
    # log the best parameters
    mlflow.log_params(study.best_params)
    # log the best error value
    mlflow.log_metric("Best_MAPE", study.best_value)

[I 2026-06-13 15:28:45,027] A new study created in memory with name: model_selection

🏃 View run polite-bird-627 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/b3bd3fa608a140919cb793a34cca2469
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run melodic-turtle-812 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/415a633a5b134f00917846876073c5d7
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run fun-chimp-46 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/6aec7e54e1814241884e8ffe2957c3b8
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:29:55,353] Trial 6 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run mercurial-shad-492 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/de7684a6fc9c42bc9a3cdf47b11e4b47
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run legendary-loon-46 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/04a04e5132b14237b5aafd64a2955b98
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run debonair-jay-714 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/0909e096a5a244eaa272dd4d8ee2120b
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run nervous-mouse-178 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/d985399b23e845478183a31227c5cb63
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run puzzled-foal-170 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/601c0884f5564e2fa5d590b06939b169
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:30:15,351] Trial 10 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:30:19,423] Trial 3 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run loud-calf-433 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/867aba62a8c943f2971306c7cd8f156a
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:30:31,373] Trial 11 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run rebellious-bass-151 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/e2738c10604c42cf87afc5ec12c767c7
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run ambitious-quail-625 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/489919dc0e0e4125854bd2f816a1af52
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run beautiful-sheep-942 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/ecddd22bb99f4c0cbbf08d0f86bf8d2e
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:30:39,367] Trial 13 finished with value: 0.4078334791191335 and parameters: {'model_name': 'RF', 'n_estimators_rf': 60, 'max_depth_rf': 4}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run thoughtful-hog-785 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/0e924ce52e2948c8a8c77be43025475f
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:30:45,664] Trial 4 finished with value: 0.5715770522655397 and parameters: {'model_name': 'RF', 'n_estimators_rf': 80, 'max_depth_rf': 3}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run dazzling-wasp-573 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/77cc6cfbaf1648ba9379b836e1db42b1
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run peaceful-asp-423 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/cef15076447d4d1a9042143011e7537c
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:30:51,378] Trial 17 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:30:53,542] Trial 8 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run smiling-wolf-998 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/450ad1aa4a324b7a81193311fc8fd32d
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run defiant-mole-639 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/626a8b40ee8c40bc84112883ac9cf93a
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:31:01,591] Trial 2 finished with value: 3.6478404325203386 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 30, 'learning_rate_gb': 0.02124312195067284}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:03,513] Trial 16 finished with value: 1.54490065574646 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 70, 'learning_rate_xgb': 0.02186709660232955, 'max_depth_xgb': 10}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run handsome-frog-0 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/fccf6efb803a4308bf7000175d9593cb
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:31:07,582] Trial 9 finished with value: 6.569002151489258 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.00013249988669503202, 'max_depth_xgb': 7}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run puzzled-moose-126 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/b98eab4761dc414387831bc2f4219490
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:31:11,418] Trial 7 finished with value: 1.26020630802236 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 50, 'learning_rate_gb': 0.03757567563114593}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run capricious-bird-175 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/56381db4b15047af8c8e51a37edd74a1
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:31:21,663] Trial 14 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:31,583] Trial 15 finished with value: 0.3252742186859446 and parameters: {'model_name': 'RF', 'n_estimators_rf': 100, 'max_depth_rf': 5}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:33,664] Trial 12 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:37,822] Trial 0 finished with value: 1.0468934952913909 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 40, 'learning_rate_gb': 0.05255940259924654}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:39,583] Trial 1 finished with value: 0.40766463665686536 and parameters: {'model_name': 'RF', 'n_estimators_rf': 40, 'max_depth_rf': 4}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:45,665] Trial 5 finished with value: 0.8144692182540894 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 90, 'learning_rate_xgb': 0.0256551739340879, 'max_depth_xgb': 10}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:53,661] Trial 18 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:31:55,421] Trial 19 finished with value: 5.148782874415494 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 80, 'learning_rate_gb': 0.0032836080599170482}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run fun-stag-95 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/4d13cea4335b4884aae6bdd842c7c899
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run judicious-hog-923 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/5f2daa0e68df495da101d0b36fc8cdeb
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:32:55,508] Trial 20 finished with value: 1.150482177734375 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 20, 'learning_rate_xgb': 0.09623988179299746, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run languid-hen-83 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/bea398c9bc5d43a9b9d52b094a29f3b2
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run treasured-mink-530 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/5e5559386f914b2f9f4204b05669d8ba
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:33:03,584] Trial 21 finished with value: 1.3889085054397583 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 50, 'learning_rate_xgb': 0.03291341247140944, 'max_depth_xgb': 7}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run fun-perch-234 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/46a6ffa835904751898abb2b058dc228
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run clumsy-squid-77 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/3b85e5691b534e8c9bf3e9969c7ee91b
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run amazing-fish-554 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/cd9f2f0003a842149d307adb1f41034e
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:33:31,597] Trial 30 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run aged-ram-917 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/13a1701974fa4107b61affa0fa3ebb41
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run angry-bass-246 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/2eaf8a3ab82546b395c1614bb4f7c395
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:33:51,497] Trial 35 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run languid-frog-525 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/914038d5410148d59daba74ce2546c55
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:33:57,621] Trial 26 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run overjoyed-hog-216 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/bccbc2c4454d4e52ae716a6bbc4bf3ee
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:02,241] Trial 23 finished with value: 0.700420081615448 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 30, 'learning_rate_xgb': 0.08195746129326739, 'max_depth_xgb': 7}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run bemused-auk-88 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/8b8d69054f754a3d852be9d1e362ddff
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:11,450] Trial 25 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run delightful-lamb-43 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/087cdcebb90a404bb35434e3440fa4e5
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:18,789] Trial 22 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run adorable-deer-138 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/bdcc6f4419e940da9a2f4c661f85e8a8
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:23,434] Trial 31 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run gentle-squid-860 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/2dede8a5b87a49798f1163576b6d2df3
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:27,429] Trial 37 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:34:29,662] Trial 29 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run gregarious-ox-145 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/5883839f2c274e64964f7b2546f9d986
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:35,579] Trial 28 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run sneaky-turtle-501 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/3022ae9fc862439b930a5aa592912842
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:34:43,511] Trial 27 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:34:45,637] Trial 24 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run zealous-smelt-332 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/76c3c7fb36804b099422080e28d2b20b
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run brawny-toad-639 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/720da9183e204c8bada6baba607de9ed
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:35:03,551] Trial 38 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run painted-mole-700 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/eb852faa6ce54af49e413bf27dea86a1
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run gifted-wolf-954 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/1d1b56f54fed4148a649c65e934dd819
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:35:17,639] Trial 32 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:35:21,643] Trial 36 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run learned-cat-259 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/a9978970f2ff4b42acb6492308577571
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:35:29,653] Trial 39 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:35:31,804] Trial 33 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:35:37,695] Trial 40 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:35:39,474] Trial 34 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run brawny-midge-835 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/912788f300bb434589cab165ee2d48eb
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:35:45,650] Trial 47 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run stylish-penguin-495 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/f01d16ca1a494cc3b7495395557949a8
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:36:00,480] Trial 42 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:36:03,569] Trial 41 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run wistful-moose-556 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/e9294ce584264d0d93ea38b14fee1456
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run popular-cub-755 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/3c704b5db0d8423499b85137d60347c6
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:36:16,636] Trial 43 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.
[I 2026-06-13 15:36:19,568] Trial 46 finished with value: 0.30698710068878476 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run auspicious-hen-461 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/5da52abdc1834fbdabdf7fce7d6cefb2
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:36:20,464] Trial 48 finished with value: 6.513248869739295 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010450391360928517}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run enchanting-panda-538 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/37160416c2434aa6bf36138f8ef82c49
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:36:29,946] Trial 44 finished with value: 6.51186519336341 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010676677487379335}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run beautiful-fawn-199 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/186012009f7541d59a463ae507b7b31e
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:36:34,306] Trial 49 finished with value: 6.513005311278629 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010490219173724082}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run clean-croc-380 at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/395eaf56605041d889761c37886ef5bd
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-13 15:36:44,321] Trial 45 finished with value: 6.515633557590679 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010060549322302224}. Best is trial 6 with value: 0.30698710068878476.

🏃 View run best_model at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0/runs/eb8fc170a2644c0f8e68ad3092013796
🧪 View experiment at: https://dagshub.com/rajputriya887/uber-demand-prediction.mlflow/#/experiments/0

In [27]:
# best value

study.best_value

0.30698710068878476

In [26]:
# best parameters

study.best_params

{'model_name': 'LR'}

In [28]:
# model value counts

study.trials_dataframe()['params_model_name'].value_counts()

params_model_name
LR      32
GBR      8
XGBR     6
RF       4
Name: count, dtype: int64

In [29]:
from optuna.visualization import (
    plot_optimization_history, 
    plot_parallel_coordinate, 
    plot_param_importances
)

In [30]:
import plotly
plot_optimization_history(study)

In [31]:
plot_parallel_coordinate(study, params=["model_name"])

In [32]:
# train the linear regression model

lr = LinearRegression()

lr.fit(X_train_encoded, y_train)

# get predictions
y_pred_train = lr.predict(X_train_encoded) 
y_pred_test = lr.predict(X_test_encoded)

# loss

mape_train = mean_absolute_percentage_error(y_train, y_pred_train)
mape_test = mean_absolute_percentage_error(y_test, y_pred_test)

print("The training error is ", mape_train)
print("The test error is ", mape_test)

The training error is  0.3174973173589058
The test error is  0.30698710068878476

In [33]:
lr.coef_

array([ 6.59266116, -2.05638952,  1.61048142,  3.5589809 ,  9.08819126,
        2.48639847,  7.8520678 , 10.1342072 , -1.11046656,  8.27602693,
        5.45456779, 10.55872532, -1.47820493,  7.18907985,  6.87749488,
       -1.37837448, -1.70783813, 13.33847201,  5.6738974 ,  3.55876455,
       11.32924195,  5.90374261,  2.88449163, -2.03676138,  2.83674402,
        2.42578855,  6.85780565, -1.94162399, -1.62963472,  0.64633354,
        0.93102079,  1.43743235,  1.61026612,  0.91215046, -0.468891  ,
        1.40961414,  0.49144781,  0.28244361,  0.18601736, -1.42136691])

In [34]:
def tune_ridge(trial):
    # hyperparameter space
    alpha = trial.suggest_float("alpha",30,100)
    
    # make the model object
    ridge = Ridge(alpha=alpha, random_state=42)
    
    # train the model
    ridge.fit(X_train_encoded, y_train)
    
    # get predictions
    y_pred = ridge.predict(X_test_encoded)
    
    # calculate loss
    loss = mean_absolute_percentage_error(y_test, y_pred)

    return loss

In [35]:
# create study

study = optuna.create_study(study_name="tune_model", direction="minimize")

[I 2026-06-13 15:42:34,920] A new study created in memory with name: tune_model

In [36]:
# optimize

study.optimize(func=tune_ridge, n_trials=100, n_jobs=-1, show_progress_bar=True)

  0%|          | 0/100 [00:00<?, ?it/s]

Best trial: 0. Best value: 0.306883:   2%|▏         | 2/100 [00:00<00:21,  4.50it/s]

[I 2026-06-13 15:42:42,074] Trial 0 finished with value: 0.3068834690871679 and parameters: {'alpha': 47.837889099666384}. Best is trial 0 with value: 0.3068834690871679.
[I 2026-06-13 15:42:42,097] Trial 2 finished with value: 0.30693799405668976 and parameters: {'alpha': 72.15170813763665}. Best is trial 0 with value: 0.3068834690871679.
[I 2026-06-13 15:42:42,103] Trial 1 finished with value: 0.30690184045643915 and parameters: {'alpha': 58.90590391480911}. Best is trial 0 with value: 0.3068834690871679.

[I 2026-06-13 15:42:42,381] Trial 7 finished with value: 0.3070429187841596 and parameters: {'alpha': 97.64361910237092}. Best is trial 0 with value: 0.3068834690871679.

[I 2026-06-13 15:42:42,253] Trial 4 finished with value: 0.3069351184392668 and parameters: {'alpha': 71.26311825898583}. Best is trial 0 with value: 0.3068834690871679.
[I 2026-06-13 15:42:42,375] Trial 6 finished with value: 0.30688566726232297 and parameters: {'alpha': 49.72384173433535}. Best is trial 0 with value: 0.3068834690871679.
[I 2026-06-13 15:42:42,174] Trial 3 finished with value: 0.30703013233646514 and parameters: {'alpha': 94.97149581559285}. Best is trial 0 with value: 0.3068834690871679.
[I 2026-06-13 15:42:42,410] Trial 5 finished with value: 0.3070062916465192 and parameters: {'alpha': 89.73439463117343}. Best is trial 0 with value: 0.3068834690871679.
[I 2026-06-13 15:42:42,543] Trial 9 finished with value: 0.30687805008833674 and parameters: {'alpha': 38.0715936349782}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,625] Trial 12 finished with value: 0.30687907243321716 and parameters: {'alpha': 42.046147330086974}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,625] Trial 8 finished with value: 0.3070503657252712 and parameters: {'alpha': 99.15575307414865}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,658] Trial 10 finished with value: 0.3068780935934023 and parameters: {'alpha': 38.686623235979056}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  16%|█▌        | 16/100 [00:01<00:04, 20.31it/s]

[I 2026-06-13 15:42:42,660] Trial 13 finished with value: 0.3068957918372502 and parameters: {'alpha': 56.00357056309339}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,661] Trial 11 finished with value: 0.30688229204239253 and parameters: {'alpha': 46.65437516121699}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,669] Trial 18 finished with value: 0.30697533988527004 and parameters: {'alpha': 82.39837552757379}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,678] Trial 14 finished with value: 0.30697796893528856 and parameters: {'alpha': 83.05243140646391}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,679] Trial 15 finished with value: 0.30699441978433784 and parameters: {'alpha': 87.00245717740547}. Best is trial 9 with value: 0.30687805008833674.

[I 2026-06-13 15:42:42,702] Trial 16 finished with value: 0.30693793333954605 and parameters: {'alpha': 72.13315630241547}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,706] Trial 17 finished with value: 0.30702110717383363 and parameters: {'alpha': 93.0248631806385}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,761] Trial 20 finished with value: 0.30688288824898724 and parameters: {'alpha': 47.27418277826841}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,786] Trial 19 finished with value: 0.3068791888589389 and parameters: {'alpha': 42.289603432384666}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  28%|██▊       | 28/100 [00:01<00:02, 24.90it/s]

[I 2026-06-13 15:42:42,790] Trial 22 finished with value: 0.30688339319397845 and parameters: {'alpha': 47.765976711395545}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,791] Trial 23 finished with value: 0.30694678986850804 and parameters: {'alpha': 74.76254671736802}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,794] Trial 21 finished with value: 0.3069018084958116 and parameters: {'alpha': 58.89137239701272}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,963] Trial 24 finished with value: 0.30688157143342526 and parameters: {'alpha': 30.745914077489516}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:42,987] Trial 25 finished with value: 0.3068797236443883 and parameters: {'alpha': 32.98860675250596}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,110] Trial 27 finished with value: 0.30688129699698974 and parameters: {'alpha': 31.035300380891016}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,157] Trial 30 finished with value: 0.3068822856260021 and parameters: {'alpha': 30.03635722325155}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,158] Trial 28 finished with value: 0.3068819329981774 and parameters: {'alpha': 30.379512538425363}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  32%|███▏      | 32/100 [00:01<00:02, 23.30it/s]

[I 2026-06-13 15:42:43,161] Trial 26 finished with value: 0.30688107410988225 and parameters: {'alpha': 31.27808709515113}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,226] Trial 29 finished with value: 0.3068814472761313 and parameters: {'alpha': 30.875507387245506}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,244] Trial 31 finished with value: 0.306882138562497 and parameters: {'alpha': 30.177962518953684}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,305] Trial 32 finished with value: 0.306880306846225 and parameters: {'alpha': 32.18272775723437}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  40%|████      | 40/100 [00:02<00:02, 24.97it/s]

[I 2026-06-13 15:42:43,347] Trial 33 finished with value: 0.3068816098925244 and parameters: {'alpha': 30.70616795613611}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,351] Trial 34 finished with value: 0.30687882043485526 and parameters: {'alpha': 34.594417382071285}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,395] Trial 35 finished with value: 0.30687805864743345 and parameters: {'alpha': 37.6298233764216}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,506] Trial 36 finished with value: 0.3068780697070122 and parameters: {'alpha': 38.46818647788058}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,531] Trial 37 finished with value: 0.30687809087071505 and parameters: {'alpha': 37.24329581149277}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,587] Trial 38 finished with value: 0.3068781205781595 and parameters: {'alpha': 38.89491102142604}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,661] Trial 41 finished with value: 0.30687809905311597 and parameters: {'alpha': 38.73146758458161}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,741] Trial 39 finished with value: 0.3068781760424262 and parameters: {'alpha': 39.25041933244586}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  44%|████▍     | 44/100 [00:02<00:02, 26.19it/s]

[I 2026-06-13 15:42:43,744] Trial 40 finished with value: 0.30687834895231486 and parameters: {'alpha': 40.049992483193286}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,750] Trial 42 finished with value: 0.3068781157113987 and parameters: {'alpha': 38.859570513613164}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,751] Trial 43 finished with value: 0.3068781068283969 and parameters: {'alpha': 38.792738710286876}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,792] Trial 45 finished with value: 0.306878051897413 and parameters: {'alpha': 38.12945031148204}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  49%|████▉     | 49/100 [00:02<00:02, 21.58it/s]

[I 2026-06-13 15:42:43,821] Trial 44 finished with value: 0.3068780571383236 and parameters: {'alpha': 38.25977347526681}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,837] Trial 47 finished with value: 0.3068780646839149 and parameters: {'alpha': 37.53435489215406}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,891] Trial 46 finished with value: 0.30687808478011386 and parameters: {'alpha': 37.29934804648836}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,920] Trial 48 finished with value: 0.3068782676690149 and parameters: {'alpha': 39.7203985409953}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:43,922] Trial 49 finished with value: 0.3068780554781764 and parameters: {'alpha': 38.2225831998314}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  57%|█████▋    | 57/100 [00:02<00:01, 27.95it/s]

[I 2026-06-13 15:42:44,052] Trial 51 finished with value: 0.3068929724155176 and parameters: {'alpha': 54.482656236300606}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,073] Trial 50 finished with value: 0.30688955009732144 and parameters: {'alpha': 52.43044646504966}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,196] Trial 52 finished with value: 0.3068897879311057 and parameters: {'alpha': 52.58149430832613}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,223] Trial 54 finished with value: 0.306890306524701 and parameters: {'alpha': 52.905713946729946}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,268] Trial 53 finished with value: 0.3068888015999836 and parameters: {'alpha': 51.94458646303282}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,276] Trial 55 finished with value: 0.3068918496139816 and parameters: {'alpha': 53.8346705677898}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,305] Trial 56 finished with value: 0.3068882952280863 and parameters: {'alpha': 51.60568585675224}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,343] Trial 57 finished with value: 0.30688861201049056 and parameters: {'alpha': 51.8183933470726}. Best is trial 9 with value: 0.30687805008833674.

[I 2026-06-13 15:42:44,347] Trial 58 finished with value: 0.30689009408709206 and parameters: {'alpha': 52.77350347839726}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,378] Trial 59 finished with value: 0.30688856628170774 and parameters: {'alpha': 51.78783265073807}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,408] Trial 60 finished with value: 0.3068913221914721 and parameters: {'alpha': 53.52303135516897}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  68%|██████▊   | 68/100 [00:03<00:01, 24.24it/s]

[I 2026-06-13 15:42:44,419] Trial 61 finished with value: 0.3068801236367815 and parameters: {'alpha': 43.92475234750609}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,467] Trial 62 finished with value: 0.30688051830237967 and parameters: {'alpha': 44.494484897325165}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,502] Trial 63 finished with value: 0.3068804212664314 and parameters: {'alpha': 44.359448683851824}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,592] Trial 65 finished with value: 0.306880641526561 and parameters: {'alpha': 44.662839160582585}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,613] Trial 64 finished with value: 0.30687911678344176 and parameters: {'alpha': 42.140493278240506}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,728] Trial 66 finished with value: 0.30688062555560747 and parameters: {'alpha': 44.64120579379009}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,838] Trial 68 finished with value: 0.30688086428339695 and parameters: {'alpha': 44.9590889568428}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,848] Trial 67 finished with value: 0.3068809529491832 and parameters: {'alpha': 45.07430269861104}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  74%|███████▍  | 74/100 [00:03<00:00, 26.08it/s]

[I 2026-06-13 15:42:44,923] Trial 70 finished with value: 0.30687863294544465 and parameters: {'alpha': 35.04778544451941}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,925] Trial 69 finished with value: 0.3068786646557596 and parameters: {'alpha': 34.966376026839555}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,942] Trial 71 finished with value: 0.3068782510310008 and parameters: {'alpha': 36.26591152218581}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,946] Trial 72 finished with value: 0.3068788179030906 and parameters: {'alpha': 34.60001136651663}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,978] Trial 74 finished with value: 0.3068786384416033 and parameters: {'alpha': 35.0335518819321}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:44,987] Trial 73 finished with value: 0.30687884598877607 and parameters: {'alpha': 34.53888563269004}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  78%|███████▊  | 78/100 [00:03<00:00, 22.41it/s]

[I 2026-06-13 15:42:45,005] Trial 76 finished with value: 0.30687913654337123 and parameters: {'alpha': 33.958237149864644}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,036] Trial 75 finished with value: 0.3068783071312019 and parameters: {'alpha': 36.03982102534768}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,073] Trial 77 finished with value: 0.3068785931220723 and parameters: {'alpha': 35.152537761113535}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,107] Trial 79 finished with value: 0.3068786060508302 and parameters: {'alpha': 35.118210519556484}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878:  93%|█████████▎| 93/100 [00:04<00:00, 39.34it/s]

[I 2026-06-13 15:42:45,203] Trial 78 finished with value: 0.306878819190776 and parameters: {'alpha': 34.59716532696562}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,206] Trial 80 finished with value: 0.30687822869005765 and parameters: {'alpha': 36.365716847856135}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,303] Trial 82 finished with value: 0.3068780622609654 and parameters: {'alpha': 37.57103246464327}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,305] Trial 81 finished with value: 0.30687879499489074 and parameters: {'alpha': 41.39933777134693}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,347] Trial 83 finished with value: 0.3068786772905328 and parameters: {'alpha': 41.090621267768384}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,429] Trial 84 finished with value: 0.30687877708693084 and parameters: {'alpha': 41.353791293165145}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,462] Trial 86 finished with value: 0.30687882937176897 and parameters: {'alpha': 41.48546777095871}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,491] Trial 85 finished with value: 0.3068788346960396 and parameters: {'alpha': 41.498659347467665}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,502] Trial 87 finished with value: 0.3068856324666273 and parameters: {'alpha': 49.69667904635364}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,609] Trial 89 finished with value: 0.30687862149629624 and parameters: {'alpha': 40.93555119078929}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,628] Trial 88 finished with value: 0.3068786732287199 and parameters: {'alpha': 41.0795469819987}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,632] Trial 90 finished with value: 0.30687903499027663 and parameters: {'alpha': 41.96472272341612}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,634] Trial 92 finished with value: 0.30687866908211786 and parameters: {'alpha': 41.068210096409516}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,651] Trial 91 finished with value: 0.3068786064643952 and parameters: {'alpha': 40.892686507560335}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,719] Trial 93 finished with value: 0.3068847009010652 and parameters: {'alpha': 48.94129180755517}. Best is trial 9 with value: 0.30687805008833674.

Best trial: 9. Best value: 0.306878: 100%|██████████| 100/100 [00:04<00:00, 24.06it/s]

[I 2026-06-13 15:42:45,776] Trial 95 finished with value: 0.30688007171111137 and parameters: {'alpha': 32.49260556846314}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,816] Trial 96 finished with value: 0.30687806569300013 and parameters: {'alpha': 37.519631629003904}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,817] Trial 94 finished with value: 0.30687805415593183 and parameters: {'alpha': 37.71565077135139}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,886] Trial 97 finished with value: 0.3068780654471596 and parameters: {'alpha': 37.52319073577453}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,898] Trial 98 finished with value: 0.3068780637145212 and parameters: {'alpha': 37.54879509703153}. Best is trial 9 with value: 0.30687805008833674.
[I 2026-06-13 15:42:45,937] Trial 99 finished with value: 0.3068781174942373 and parameters: {'alpha': 37.02500445972848}. Best is trial 9 with value: 0.30687805008833674.

In [37]:
# best parameters

study.best_params

{'alpha': 38.0715936349782}

In [38]:
# best value

study.best_value

0.30687805008833674